tosca_definitions_version: cloudify_dsl_1_3

description: >
  This Blueprint configures an existing HAProxy by updating the config
  file: /etc/haproxy/haproxy.cfg and restarting the haproxy service.
  Users need to provide a new config file and make sure it's
  here: resources/haproxy.cfg.

imports:
  - http://www.getcloudify.org/spec/cloudify/4.5.5.dev1/types.yaml
  - http://www.getcloudify.org/spec/fabric-plugin/1.5.1/plugin.yaml

inputs:
  host_string:
    description: >
      The host of the HAProxy.
  user:
    description: >
      User name used when SSH-ing into the started HAProxy machine.
    default: centos
  key_filename:
    description: >
      Path to a private key that resided on the management machine.
      SSH-ing into agent machines will be done with this key.
    default: /etc/cloudify/ssh_key

node_templates:
  haproxy:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          implementation: fabric.fabric_plugin.tasks.run_task
          inputs:
            tasks_file: scripts/haproxy.py
            task_name: configure
            fabric_env:
              host_string: { get_input: host_string }
              user: { get_input: user }
              key_filename: { get_input: key_filename }
